---
 - name: Download dokuwiki tarball
   get_url: url=https://download.dokuwiki.org/src/dokuwiki/dokuwiki-oldstable.tgz dest=/tmp/dokuwiki-oldstable.tgz

 - name: Unpack tarball
   command: tar -xvf dokuwiki-oldstable.tgz chdir=/tmp

 - name: Move dokuwiki
   shell: cp -af /tmp/dokuwiki-*/* {{ web_dir }}
 
 - name: Remove tmp files
   shell: rm -rf /tmp/dokuwiki-*
   
 - name: Fix permissions
   shell: chown -R {{ web_group }}:{{ web_owner }} {{ web_dir }}

 - name: Restart nginx
   service: name=nginx state=restarted

 - name: Restart php-fpm
   service: name=php7.0-fpm state=restarted
