---
- name: Install PHP
  include: php.yaml

- name: Install Nginx
  include: nginx.yaml

- name: Install Dokuwiki
  include: dokuwiki.yaml

- name: FW configuration
  include: fw.yaml

- name: Creating hostname
  shell: echo "192.168.100.11   wiki.project" >> /etc/hosts
