---
- name: Update apt-cache
  apt: update_cache=yes

- name: Install php-fpm and deps
  apt: name={{ item }} state=present
  with_items:
  - php
  - php-curl
  - php-fpm
  - php-mbstring 
  - php-json 
  - php-xml 
  - php-common 
